# Generated by Django 4.1.2 on 2022-11-01 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(max_length=30, unique=True, verbose_name="증권사"),
                ),
                ("is_deposit", models.BooleanField(verbose_name="입/출금")),
                ("amount", models.PositiveIntegerField(verbose_name="입/출금 금액")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="입/출금 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
        ),
    ]
