# Generated by Django 4.1.2 on 2022-11-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trader",
            old_name="company",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="trader",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="trader",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trader",
            name="is_deposit",
        ),
        migrations.RemoveField(
            model_name="trader",
            name="user",
        ),
    ]
