# Generated by Django 4.1.2 on 2022-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_asset_isin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                choices=[
                    ("미국 주식", "미국 주식"),
                    ("미국섹터 주식", "미국섹터 주식"),
                    ("선진국 주식", "선진국 주식"),
                    ("신흥국 주식", "신흥국 주식"),
                    ("전세계 주식", "전세계 주식"),
                    ("부동산 / 원자재", "부동산 / 원자재"),
                    ("채권 / 현금", "채권 / 현금"),
                ],
                max_length=50,
                unique=True,
                verbose_name="자산그룹",
            ),
        ),
    ]
