# Generated by Django 4.1.2 on 2022-11-01 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="principal",
            field=models.PositiveBigIntegerField(default=1, verbose_name="투자원금"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, verbose_name="계좌번호"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="계좌주",
            ),
        ),
    ]
