# Generated by Django 4.1.2 on 2022-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_principal_alter_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.CharField(default="내 집 마련", max_length=80, verbose_name="계좌명"),
            preserve_default=False,
        ),
    ]
