# Generated by Django 4.1.2 on 2022-11-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("traders", "0002_rename_company_trader_name_remove_trader_amount_and_more"),
        ("accounts", "0003_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="trader",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="traders.trader",
                verbose_name="증권사",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="계좌",
                    ),
                ),
            ],
        ),
    ]
