# Generated by Django 4.1.2 on 2022-11-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_trader_history"),
        ("accounts", "0004_remove_account_user_account_trader_and_more"),
    ]

    operations = []
