# Generated by Django 4.1.2 on 2022-11-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_remove_account_user_alter_account_name_accountowner_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.accountowner",
                verbose_name="계좌주",
            ),
        ),
    ]
