# Generated by Django 4.1.2 on 2022-11-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_account_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(max_length=80, verbose_name="계좌번호"),
                ),
                ("user_name", models.CharField(max_length=80, verbose_name="유져명")),
                ("transfer_amount", models.PositiveIntegerField(verbose_name="거래금액")),
            ],
        ),
    ]
